# Generated by Django 4.2.4 on 2023-09-21 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_remove_anime_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='mal_id',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='users',
            field=models.ManyToManyField(related_name='animes', to=settings.AUTH_USER_MODEL),
        ),
    ]
