# Generated by Django 4.2.4 on 2023-09-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_anime_mal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='mal_id',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='users',
        ),
        migrations.AddField(
            model_name='anime',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
