# Generated by Django 4.2.4 on 2023-09-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_anime_mal_id_remove_anime_users_anime_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='mal_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
