# Generated by Django 4.2.4 on 2023-09-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_anime_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='airing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='anime',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='anime',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
