# Generated by Django 4.2.4 on 2023-09-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_anime_airing_anime_image_url_anime_title_anime_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='airing',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='mal_id',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='title',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='url',
        ),
        migrations.AddField(
            model_name='anime',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
