# Generated by Django 4.2.4 on 2023-09-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_anime_airing_remove_anime_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='mal_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
